# SITE
url: 'https://absolute-rat.github.io'
baseurl: ''
permalink: /:title/

title: 'RATS FOR SALE'
subtitle: 'rats and rat accessories'
description: 'RATS AT LOW LOW PRICES'

# build
highlighter: rouge
exclude: ['LICENSE', 'README.md']

# theme
featured-height: 200 # featured image height; options: intiger, default: false (300px)

# pixelate.js - class="pixelate", pixelateAll overides all settings
pixelate-featured: true # pixelate all header images; options: true, false, default: off false (off)
pixelate-all: false # pixelate all images; options: true, false, default: false (off)
