# SITE
url: 'https://absolute-rat.github.io'
baseurl: ''
permalink: /:title/

title: 'RATS FOR SALE'
subtitle: '<a href="https://jekyllrb.com/">#Jekyll</a> <a href="https://www.tumblr.com/search/seapunk">#Seapunk</a> <a href="https://int10h.org/oldschool-pc-fonts/fontlist/#ibmmda">#Terminal</a>'
description: 'RATS AT LOW LOW PRICES'

# build
highlighter: rouge
exclude: ['LICENSE', 'README.md']

# theme
featured-height: 200 # featured image height; options: intiger, default: false (300px)

# pixelate.js - class="pixelate", pixelateAll overides all settings
pixelate-featured: true # pixelate all header images; options: true, false, default: off false (off)
pixelate-all: false # pixelate all images; options: true, false, default: false (off)
